version: "3.9"

services:
  database:
    container_name: database
    image: mysql:8.0
#    platform: linux/x86_64     # for Intel Chips with WSL2 Enabled
    platform: linux/arm64/v8    # for Mac Silicon Chips
    restart: always
    environment:
      MYSQL_DATABASE: auth_side
      MYSQL_USER: auth_side
      MYSQL_PASSWORD: auth_side_pass
      MYSQL_ROOT_PASSWORD: auth_side_pass
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    restart: on-failure
    ports:
      - "9090:9090"
    environment:
      - DATABASE_USERNAME=auth_side
      - DATABASE_PASSWORD=auth_side_pass
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=3307
    depends_on:
      - database