server:
  port: 9090

logging:
  level:
    web: debug

spring:
  datasource:
    username: ${DATABASE_USERNAME:auth_side}
    password: ${DATABASE_PASSWORD:auth_side_pass}
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/auth_side
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    changeLog: "classpath:database/configuration.yaml"
    drop-first: ${LIQUIBASE_ENABLE_DROP_FIRST:true}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc:
  packagesToScan: com.agitrubard.authside
  cache:
    disabled: false
  swagger-ui:
    path: /public/swagger-ui.html
  api-docs:
    path: /public/api/docs

info:
  application:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health
      base-path: /public/actuator
